import { Request, Response, NextFunction } from 'express';
import mongoose from 'mongoose';

// Import all Domain Models to dynamically resolve their collection names
import { ApmTrace, ApmService } from '../models/Apm';
import { RumTrace, RumService } from '../models/Rum';
import { LogEvent } from '../models/Log';
import { TaskRun, TaskService } from '../models/Task';
import { VpsRun, Vps } from '../models/Vps';
import { DbMetric, DatabaseService } from '../models/Database';
import { MonitorRun, Monitor } from '../models/Monitor';
import { ErrorGroup } from '../models/Error';
import { RuntimeMetric } from '../models/RuntimeMetric';
import { WebEvent, Website } from '../models/Web';

// ============================================================================
// ENTERPRISE TARGET MAPPING (Dynamic)
// Dynamically extracts the exact physical collection names generated by Mongoose
// preventing any mismatch bugs if schema naming configurations change.
// ============================================================================
const COLLECTION_MAP: Record<string, { event: string; service: string | null }> = {
  apm: { event: ApmTrace.collection.name, service: ApmService.collection.name },
  logs: { event: LogEvent.collection.name, service: null }, // Logs have no strict parent service
  vps: { event: VpsRun.collection.name, service: Vps.collection.name },
  database: { event: DbMetric.collection.name, service: DatabaseService.collection.name },
  uptime: { event: MonitorRun.collection.name, service: Monitor.collection.name },
  rum: { event: RumTrace.collection.name, service: RumService.collection.name },
  task: { event: TaskRun.collection.name, service: TaskService.collection.name },
  errors: { event: ErrorGroup.collection.name, service: null },
  runtime: { event: RuntimeMetric.collection.name, service: ApmService.collection.name },
  web: { event: WebEvent.collection.name, service: Website.collection.name }
};

// ============================================================================
// SECURITY & INFERENCE BLACKLISTS
// Prevent sensitive or internal database fields from appearing in the UI schema
// ============================================================================
const SERVICE_BLACKLIST = ['_id', 'apiKey', 'ownerId', 'createdAt', 'updatedAt', '__v'];
const EVENT_BLACKLIST = ['ownerId', '__v'];

// ============================================================================
// TTL CACHE SYSTEM
// Prevents database DDoS if multiple users open the editor concurrently.
// Schemas rarely change minute-to-minute, so a 15-minute TTL is highly optimal.
// ============================================================================
interface CacheEntry {
  data: Record<string, any[]>;
  expiresAt: number;
}
let schemaCache: CacheEntry | null = null;
const CACHE_TTL_MS = 15 * 60 * 1000; // 15 minutes

// ============================================================================
// INFERENCE ENGINE
// ============================================================================

/**
 * Native driver sampling. Bypasses Mongoose overhead and uses reverse _id sorting 
 * to instantly grab the 50 most recent documents (guaranteed O(1) time complexity 
 * due to native _id index), representing the most up-to-date shape of the data.
 */
async function sampleCollection(collectionName: string | null, limit = 50): Promise<any[]> {
  if (!collectionName) return [];

  try {
    const db = mongoose.connection.db;
    if (!db) throw new Error("Database not connected");

    // Check if collection actually exists to prevent Native Driver errors
    const collections = await db.listCollections({ name: collectionName }).toArray();
    if (collections.length === 0) return [];

    return await db.collection(collectionName)
      .find({})
      .sort({ _id: -1 })
      .limit(limit)
      .toArray();
  } catch (error) {
    console.warn(`[Schema Engine] Failed to sample collection ${collectionName}:`, error);
    return [];
  }
}

/**
 * Deep recursive traversal to map JSON documents to MQL dot-notation paths.
 */
function inferSchemaFromDocs(docs: any[], prefix = '', blacklist: string[] = []): { field: string; type: string; desc: string }[] {
  const schemaMap = new Map<string, string>();

  function traverse(obj: any, currentPath: string) {
    if (obj === null || obj === undefined) return;

    if (Array.isArray(obj)) {
      if (obj.length > 0) {
        const first = obj[0];
        if (first && typeof first === 'object' && !(first instanceof Date)) {
          // If it's an array of objects, MQL queries it via dot notation: arrayField.childField
          traverse(first, currentPath);
        } else {
          schemaMap.set(currentPath, `array<${typeof first}>`);
        }
      } else {
        if (!schemaMap.has(currentPath)) schemaMap.set(currentPath, 'array');
      }
      return;
    }

    if (typeof obj === 'object') {
      // Handle native BSON types
      if (obj instanceof Date) {
        schemaMap.set(currentPath, 'date');
      } else if (obj._bsontype === 'ObjectID' || obj instanceof mongoose.Types.ObjectId) {
        schemaMap.set(currentPath, 'objectId');
      } else {
        // Standard Object
        for (const [key, value] of Object.entries(obj)) {
          // Ignore internal MongoDB fields universally
          if (key === '__v') continue;

          // Apply the security blacklist to root-level fields
          if (currentPath === '' && blacklist.includes(key)) continue;

          const newPath = currentPath ? `${currentPath}.${key}` : `${prefix}${key}`;
          traverse(value, newPath);
        }
      }
      return;
    }

    // Primitives (string, number, boolean)
    schemaMap.set(currentPath, typeof obj);
  }

  // Scan all sampled docs to build a comprehensive map of all possible fields.
  // FIX: Starting traversal with an empty string '' as the currentPath ensures 
  // our prefix logic applies correctly without doubling up the dots (e.g. service.._id).
  for (const doc of docs) {
    traverse(doc, '');
  }

  const result = [];
  for (const [field, type] of schemaMap.entries()) {
    if (!field) continue; // Safety net for empty roots

    result.push({
      field,
      type,
      desc: `Auto-detected ${type}`
    });
  }

  // Alphabetical sort for professional UI presentation
  return result.sort((a, b) => a.field.localeCompare(b.field));
}

// ============================================================================
// MAIN CONTROLLER
// ============================================================================
export const getDynamicSchema = async (req: Request, res: Response, next: NextFunction) => {
  try {
    // 1. Check TTL Cache
    const now = Date.now();
    if (schemaCache && schemaCache.expiresAt > now) {
      return res.json({ schema: schemaCache.data });
    }

    const dynamicSchema: Record<string, any[]> = {};

    // 2. Concurrently scan all target domains
    const targetKeys = Object.keys(COLLECTION_MAP);

    await Promise.all(targetKeys.map(async (target) => {
      const config = COLLECTION_MAP[target];

      // Parallel fetch from Native DB Driver
      const [eventDocs, serviceDocs] = await Promise.all([
        sampleCollection(config.event, 50),
        sampleCollection(config.service, 10) // Automatically resolves to [] if config.service is null
      ]);

      // 3. Infer standard event fields (Root level) with event blacklist
      const eventSchema = inferSchemaFromDocs(eventDocs, '', EVENT_BLACKLIST);

      // 4. Infer joined service fields (Prefixed with 'service.') securely filtering sensitive properties
      const serviceSchema = inferSchemaFromDocs(serviceDocs, 'service.', SERVICE_BLACKLIST);

      // 5. Merge and save to dictionary
      dynamicSchema[target] = [...eventSchema, ...serviceSchema];
    }));

    // 6. Update Cache
    schemaCache = {
      data: dynamicSchema,
      expiresAt: now + CACHE_TTL_MS
    };

    res.json({ schema: dynamicSchema });
  } catch (error) {
    next(error);
  }
};